### ISSUE TITLE
Error running example project

### ISSUE THREAD

**Issue by brightfuture** [dobster/P2PShareKit#2]
as follows: 
> 2020-12-10 10:37:17.307649+0800 p2pShareKitDemo[18518:5790389] [listener] Ready
> 2020-12-10 10:37:17.309910+0800 p2pShareKitDemo[18518:5790389] [listener] Error: -65555: NoAuth
> 2020-12-10 10:37:17.310002+0800 p2pShareKitDemo[18518:5790389] [listener] restarting
> 2020-12-10 10:37:17.310382+0800 p2pShareKitDemo[18518:5790389] [listener] Cancelled
> 2020-12-10 10:37:17.310543+0800 p2pShareKitDemo[18518:5790389] [listener] Waiting: POSIXErrorCode: Network is down

**Comment by dobster** [comment]
Added the new Local Network Usage Description and Bonjour Services to the Info.plist for the demo project, as this is now required for iOS 14.

**Comment by brightfuture** [comment]
great, thanks !

**Comment by dobster** [comment]
no problem, thanks for reporting!
